import avatar from '../assets/candidate/Avatar.svg'

export const demoCandidate = {
  firstName: 'Sarah', lastName: 'Johnson', headline: 'Registered Nurse, BSN', location: 'New York, NY', photo: avatar,
  summary: 'Dedicated registered nurse with 8 years of experience in intensive care and emergency medicine. Passionate about patient-centered care with strong clinical assessment skills.',
  professionalInformation: { yearsOfExperience: '8', currentJobTitle: 'ICU Registered Nurse', currentEmployer: 'City General Hospital', specialty: 'ICU', licenseNumber: 'RN-123456', licenseState: 'NY' },
  workExperience: [
    { id: 'work-1', jobTitle: 'ICU Registered Nurse', employerName: 'City General Hospital', startYear: '2020', currentlyWorking: true },
    { id: 'work-2', jobTitle: 'ER Nurse', employerName: 'Memorial Health', startYear: '2017', endYear: '2019' },
  ],
  education: [
    { id: 'edu-1', degree: 'BSN', fieldOfStudy: 'Nursing', institutionName: 'NYU', graduationYear: '2016' },
    { id: 'edu-2', degree: 'Associate', fieldOfStudy: 'Nursing', institutionName: 'Hudson Community College', graduationYear: '2014' },
  ],
  skills: [{ name: 'Patient Care' }, { name: 'Critical Care' }, { name: 'ICU' }, { name: 'EMR' }, { name: 'Clinical Documentation' }],
  certifications: [{ id: 'cert-1', certificationName: 'Basic Life Support (BLS)', issuingOrganization: 'American Heart Association', issueDate: '2025-01-01', expiryDate: '2027-01-01' }, { id: 'cert-2', certificationName: 'Advanced Cardiovascular Life Support (ACLS)', issuingOrganization: 'American Heart Association', doesNotExpire: true }],
}
export const demoJobs = [
  { id: 'icu-registered-nurse', title: 'ICU Registered Nurse', hospital: 'City General Hospital', location: 'New York, NY', type: 'Full-time', specialty: 'Critical Care', posted: '2026-09-14', salary: '$85,000–$110,000 / year', shift: 'Day / Night', description: 'We are seeking an experienced ICU Registered Nurse to join our critical care team at City General Hospital. The ideal candidate will have strong clinical assessment skills, experience with ventilator management, and the ability to work effectively in a fast-paced intensive care environment.', responsibilities: ['Provide direct patient care and monitor vital signs.', 'Administer medications and document patient progress.', 'Collaborate with physicians and the multidisciplinary healthcare team.'], requirements: ['Active RN license in New York', 'BSN degree required; MSN preferred', 'Minimum 3 years ICU experience', 'BLS and ACLS certification required', 'Experience with electronic medical records', 'Strong critical thinking skills', 'Excellent communication abilities'] },
  { id: 'emergency-room-nurse', title: 'Emergency Room Nurse', hospital: 'Memorial Health System', location: 'Boston, MA', type: 'Full-time', specialty: 'Emergency Medicine', posted: '2026-09-11', salary: '$80,000–$105,000 / year', shift: 'Rotating', description: 'Join an experienced emergency care team delivering compassionate, timely care to patients of all ages.', responsibilities: ['Triage and assess incoming patients.', 'Coordinate care during emergency procedures.', 'Maintain accurate clinical documentation.'], requirements: ['Active Massachusetts RN license', 'Two years of emergency nursing experience', 'Current BLS and ACLS certification'] },
  { id: 'travel-nurse-icu', title: 'Travel Nurse – ICU', hospital: 'National Health Staffing', location: 'Various locations', type: 'Contract', specialty: 'Critical Care', posted: '2026-09-09', salary: '$2,400–$3,100 / week', shift: 'Night', description: 'Bring your critical care expertise to a 13-week travel assignment with supportive clinical teams and flexible placement options.', responsibilities: ['Care for critically ill patients.', 'Support safe handoffs between care teams.', 'Adapt to local clinical protocols.'], requirements: ['Active RN license or compact license', 'Two years of recent ICU experience', 'BLS and ACLS certification'] },
  { id: 'critical-care-nurse', title: 'Critical Care Nurse', hospital: 'Memorial Health', location: 'Brooklyn, NY', type: 'Contract', specialty: 'Critical Care', posted: '2026-09-12', salary: '$60–$75 / hour', shift: 'Day', description: 'Deliver individualized nursing care in a collaborative critical care department.', responsibilities: ['Develop patient care plans.', 'Monitor and report changes in patient conditions.', 'Educate patients and families.'], requirements: ['Active New York RN license', 'Three years of critical care experience', 'Current ACLS certification'] },
  { id: 'pediatric-nurse', title: 'Pediatric Nurse', hospital: 'Children’s Medical Center', location: 'Queens, NY', type: 'Part-time', specialty: 'Pediatrics', posted: '2026-09-08', salary: '$42–$55 / hour', shift: 'Day', description: 'Provide family-centered care to children in a welcoming pediatric unit.', responsibilities: ['Assess pediatric patients.', 'Support families throughout treatment.', 'Collaborate with pediatric specialists.'], requirements: ['Active New York RN license', 'Pediatric nursing experience', 'BLS and PALS certification'] },
  { id: 'clinic-rn', title: 'Clinic Registered Nurse', hospital: 'Riverside Clinic', location: 'Jersey City, NJ', type: 'Per Diem', specialty: 'Primary Care', posted: '2026-09-10', salary: '$45–$60 / hour', shift: 'Day', description: 'Support preventive care and outpatient services in our community clinic.', responsibilities: ['Perform routine assessments.', 'Coordinate follow-up care.', 'Provide patient education.'], requirements: ['Active New Jersey RN license', 'Current BLS certification'] },
  { id: 'home-health-nurse', title: 'Home Health Nurse', hospital: 'Community Care Partners', location: 'Newark, NJ', type: 'Full-time', specialty: 'Home Healthcare', posted: '2026-09-07', salary: '$78,000–$92,000 / year', shift: 'Day', description: 'Help patients recover at home through skilled, compassionate nursing care.', responsibilities: ['Conduct home visits.', 'Coordinate recovery plans with care teams.'], requirements: ['Active RN license', 'Home care experience'] },
  { id: 'telehealth-nurse', title: 'Telehealth Nurse', hospital: 'Connected Health', location: 'Remote', type: 'Part-time', specialty: 'Primary Care', posted: '2026-09-06', salary: '$38–$48 / hour', shift: 'Flexible', description: 'Support patients remotely with clinical guidance and care coordination.', responsibilities: ['Assess patient needs remotely.', 'Coordinate referrals and follow-up care.'], requirements: ['Active compact RN license', 'Strong communication skills'] },
  { id: 'surgical-rn', title: 'Surgical Registered Nurse', hospital: 'Valley Medical Center', location: 'Albany, NY', type: 'Full-time', specialty: 'Surgery', posted: '2026-09-05', salary: '$82,000–$102,000 / year', shift: 'Day', description: 'Join a perioperative team supporting safe surgical care.', responsibilities: ['Prepare patients for procedures.', 'Support surgical recovery.'], requirements: ['Active New York RN license', 'Perioperative experience'] },
  { id: 'mental-health-rn', title: 'Mental Health Nurse', hospital: 'Northwell Medical', location: 'Queens, NY', type: 'Full-time', specialty: 'Mental Health', posted: '2026-09-04', salary: '$83,000–$100,000 / year', shift: 'Rotating', description: 'Provide compassionate behavioral healthcare in a multidisciplinary team.', responsibilities: ['Coordinate individual care plans.', 'Support patient wellbeing.'], requirements: ['Active RN license', 'Behavioral health experience'] },
]
export const demoResumes = [
  { id: 'resume-3', name: 'Sarah_Johnson_Resume_v3.pdf', uploaded: '2025-01-15', status: 'Approved', active: true, url: '/candidate-demo-resume.pdf', demo: true },
  { id: 'resume-2', name: 'Sarah_Johnson_Resume_v2.pdf', uploaded: '2024-11-20', status: 'Archived', active: false, url: '/candidate-demo-resume.pdf', demo: true },
  { id: 'resume-1', name: 'Sarah_Johnson_Resume_v1.pdf', uploaded: '2024-09-05', status: 'Rejected', active: false, url: '/candidate-demo-resume.pdf', demo: true },
  { id: 'resume-0', name: 'Sarah_Johnson_Resume_v0.pdf', uploaded: '2024-07-01', status: 'Archived', active: false, url: '/candidate-demo-resume.pdf', demo: true },
]
export const demoApplications = demoJobs.slice(1, 9).map((job, index) => ({ id: `application-${index + 1}`, jobId: job.id, resumeId: 'resume-3', applied: `2026-09-${String(12 - index).padStart(2, '0')}`, status: ['Under Review', 'Interview', 'Shortlisted', 'Rejected', 'Hired', 'Applied', 'Under Review', 'Interview'][index] }))
export const demoActivities = [
  { id: 'activity-1', icon: 'send-horizontal', text: 'Application submitted – Emergency Room Nurse at Memorial Health System', time: '2 hours ago' },
  { id: 'activity-2', icon: 'eye-off', text: 'Profile viewed by Memorial Health', time: '1 day ago' },
  { id: 'activity-3', icon: 'circle-check', text: 'Resume approved', time: '3 days ago' },
  { id: 'activity-4', icon: 'eye-off', text: 'Profile viewed by Northside Clinic', time: '4 days ago' },
  { id: 'activity-5', icon: 'send-horizontal', text: 'Application submitted – Surgical RN at Valley Medical Center', time: '1 week ago' },
]
export const demoPrivacy = { maskContact: true, searchable: true, shareSavedJobs: false, resumeVisible: true, openToWork: true, emailNotifications: true, twoFactor: false }
export const demoPerformance = [{ label: 'Mon', value: 12 }, { label: 'Tue', value: 19 }, { label: 'Wed', value: 14 }, { label: 'Thu', value: 24 }, { label: 'Fri', value: 17 }, { label: 'Sat', value: 31 }, { label: 'Sun', value: 25 }]
export const applicationStatuses = ['Applied', 'Under Review', 'Shortlisted', 'Interview', 'Rejected', 'Hired']
export const demoMetrics = { profileViews: 142, profileStrength: 85, timesUnlocked: 15 }
export const recommendedJobIds = ['icu-registered-nurse', 'critical-care-nurse', 'travel-nurse-icu']
