import { useMemo, useState } from 'react'
import {
  ArrowRight, Check, CircleCheck, Clock3, FileCheck2, FileText, Filter, Heart,
  LockKeyhole, Search, ShieldCheck, Upload, UserRoundCheck, Users, X,
} from 'lucide-react'

const flow = [
  ['candidateRegister','Candidate','Create candidate account','Register with a name, email, and password.'],
  ['candidateVerify','Candidate','Verify email address','Confirm the email code and activate the candidate account.'],
  ['candidateOnboard','Candidate','Complete profile and upload resume','Finish the nine profile steps and submit a resume.'],
  ['resumeApprove','Admin','Review and approve resume','Review the submitted resume so the candidate can apply.'],
  ['recruiterRegister','Recruiter','Create recruiter account','Register a hiring organization and verify the email.'],
  ['orgDocuments','Recruiter','Upload organization documents','Add the registration certificate for verification.'],
  ['orgApprove','Admin','Review and approve organization','Review submitted documents and approve the recruiter.'],
  ['jobCreate','Recruiter','Create a job posting','Submit an opening for administrative review.'],
  ['jobApprove','Admin','Approve job posting','Approve the job so it appears in candidate job search.'],
  ['apply','Candidate','Find job and submit application','Apply with the approved resume and a cover letter.'],
  ['pipeline','Recruiter','Review applicant and update status','Move the application to Under Review, then Shortlisted.'],
  ['notification','Candidate','Read application update','Open the notification and see the latest application status.'],
  ['unlock','Recruiter','Search and unlock a candidate','Open a candidate profile and use one sample credit.'],
  ['checkout','Recruiter','Purchase a credit plan','Complete a simulated checkout and add credits.'],
  ['adminReview','Admin','Review platform activity','Confirm the job, application, and purchase in operations.'],
]

const defaults = {
  candidateRegistered:false, candidateVerified:false, candidateOnboard:false, resumeApprove:false,
  recruiterRegistered:false, orgDocuments:false, orgApprove:false, jobCreate:false,
  jobApprove:false, apply:false, pipeline:false, notification:false, unlock:false,
  checkout:false, adminReview:false, appStatus:'Applied', credits:240, savedJobs:1,
  teamInvites:[], privacy:{discoverable:true, contactVisible:false, resumeVisible:false},
  settings:{maintenance:false, expiry:60},
}

function Pill({ children, tone='slate' }) {
  const tones={slate:'bg-slate-100 text-slate-600',teal:'bg-teal-50 text-teal-800',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-800',blue:'bg-blue-50 text-blue-800',violet:'bg-violet-50 text-violet-800'}
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${tones[tone]}`}>{children}</span>
}

function Panel({ title, subtitle, action, children }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div>{action}</div><div className="p-5">{children}</div></section>
}

function Action({ children, onClick, disabled=false, secondary=false }) {
  return <button disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-xl px-3.5 py-2.5 text-xs font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${secondary?'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50':'bg-teal-700 text-white hover:bg-teal-800'}`}>{children}</button>
}

function Table({ headers, rows }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[590px] text-left"><thead><tr className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{headers.map(x=><th key={x} className="px-3 pb-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,i)=><tr key={i} className="text-xs text-slate-600">{row.map((cell,j)=><td key={j} className="px-3 py-3.5">{cell}</td>)}</tr>)}</tbody></table></div>
}

function Toggle({ label, value, onChange }) {
  return <button onClick={()=>onChange(!value)} className="flex w-full items-center justify-between gap-4 rounded-xl border border-slate-100 px-4 py-3 text-left"><span><span className="block text-sm font-semibold text-slate-800">{label}</span><span className="mt-1 block text-xs text-slate-500">{value?'Enabled':'Disabled'}</span></span><span className={`relative h-6 w-11 rounded-full transition ${value?'bg-teal-700':'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></span></button>
}

function Journey({ role, demo, update }) {
  const current=flow.find(([key])=>!demo[key])
  const currentIndex=current?flow.indexOf(current):flow.length
  const done=flow.filter(([key])=>demo[key]).length
  return <div className="space-y-5">
    <div className="rounded-2xl bg-gradient-to-r from-[#103f4c] to-[#17817b] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-100">Guided prototype</p><h2 className="mt-2 text-2xl font-bold">A-to-Z hiring journey</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-teal-50/90">Move between Candidate, Recruiter, and Admin from the workspace switcher. Each action updates shared sample data so you can show the whole product story.</p></div><div className="rounded-2xl bg-white/10 px-4 py-3 text-center"><p className="text-2xl font-bold">{done}<span className="text-base font-medium text-teal-100">/{flow.length}</span></p><p className="text-[10px] uppercase tracking-widest text-teal-100">steps complete</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white transition-all" style={{width:`${done/flow.length*100}%`}}/></div></div>
    <Panel title={current?'Your next step':'Journey complete'} subtitle={current?`Step ${currentIndex+1} of ${flow.length} · Switch to the ${current[1]} workspace to continue.`:'All sample steps are complete. Reset the preview to run it again.'} action={<Action secondary onClick={()=>update({...defaults})}><span className="inline-flex items-center gap-2"><X size={14}/>Reset demo</span></Action>}>
      {current?<div className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-teal-50/70 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-teal-700"><CircleCheck size={19}/></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{current[2]}</h3><Pill tone={role===current[1]?'teal':'amber'}>{role===current[1]?'Ready in this workspace':`Switch to ${current[1]}`}</Pill></div><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-600">{current[3]}</p></div></div><Action disabled={role!==current[1]} onClick={()=>update({...demo,[current[0]]:true})}>Complete sample step<ArrowRight size={14}/></Action></div>:<p className="text-sm text-emerald-700">Candidate application, recruiter hiring, and admin operations have all been demonstrated.</p>}
    </Panel>
    <Panel title="Journey map" subtitle="The prototype carries sample state across all three portal views."><div className="space-y-1">{flow.map(([key,persona,label,description],i)=>{const complete=Boolean(demo[key]);const active=i===currentIndex;return <div key={key} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${active?'bg-teal-50':complete?'':'hover:bg-slate-50'}`}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${complete?'bg-emerald-100 text-emerald-700':active?'bg-teal-700 text-white':'bg-slate-100 text-slate-400'}`}>{complete?<Check size={15}/>:i+1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`text-sm font-semibold ${complete?'text-slate-500':'text-slate-800'}`}>{label}</p><Pill tone={persona===role?'teal':'slate'}>{persona}</Pill></div><p className="mt-0.5 text-xs text-slate-500">{description}</p></div>{complete&&<span className="text-[10px] font-semibold uppercase tracking-wider text-emerald-700">Done</span>}</div>})}</div></Panel>
  </div>
}

function CandidateScreen({ page, demo, update, onAction }) {
  const [search,setSearch]=useState('')
  if(page==='A–Z Flow') return <Journey role="Candidate" demo={demo} update={update}/>
  if(page==='Find jobs') return <Panel title="Find your next role" subtitle="Explore verified healthcare opportunities." action={<button className="rounded-xl border border-slate-200 p-2 text-slate-500"><Filter size={15}/></button>}><div className="mb-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Role, specialty, or hospital" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-teal-500"/></div><select className="rounded-xl border border-slate-200 bg-white px-3 text-xs text-slate-600"><option>All locations</option><option>Bengaluru</option><option>Hyderabad</option></select></div><div className="space-y-3">{[['Staff Nurse · ICU','Northstar Medical Center','Bengaluru · Full time','₹6–8 LPA'],['Clinical Nurse','Green Valley Hospital','Hyderabad · Full time','₹5–7 LPA'],['Nurse Practitioner','CityCare Health','Pune · Contract','₹8–10 LPA']].filter(x=>x.join(' ').toLowerCase().includes(search.toLowerCase())).map(job=><article key={job[0]} className="flex flex-wrap items-center gap-4 rounded-xl border border-slate-100 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-800"><BriefcaseIcon/></div><div className="min-w-48 flex-1"><h3 className="text-sm font-bold text-slate-900">{job[0]}</h3><p className="mt-1 text-xs text-slate-500">{job[1]} · {job[2]}</p></div><span className="text-xs font-semibold text-slate-700">{job[3]}</span><Action onClick={()=>update({...demo,apply:true})}>Apply</Action></article>)}</div></Panel>
  if(page==='Applications') return <Panel title="My applications" subtitle="See where each application is in the hiring process."><Table headers={['Position','Hospital','Applied','Status']} rows={[["Staff Nurse · ICU","Northstar Medical Center","Oct 08, 2026",<Pill tone={demo.notification?'violet':'blue'}>{demo.notification?demo.appStatus:demo.apply?'Applied':'Not submitted'}</Pill>],["Clinical Nurse","Green Valley Hospital","Oct 04, 2026",<Pill tone="violet">Interview</Pill>],["Registered Nurse","Lakeside Medical","Sep 28, 2026",<Pill tone="green">Shortlisted</Pill>]]}/><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><BellIcon/> Status changes from the recruiter appear here with a notification.</div></Panel>
  if(page==='Saved jobs') return <Panel title="Saved opportunities" subtitle={`${demo.savedJobs} roles saved for later.`}><div className="space-y-3">{[['Staff Nurse · ICU','Northstar Medical Center','Bengaluru, Karnataka'],['Clinical Nurse','Green Valley Hospital','Hyderabad, Telangana']].slice(0,Math.max(1,demo.savedJobs)).map(job=><div key={job[0]} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-100 p-4"><Heart className="text-rose-500" size={17}/><div className="flex-1"><b className="text-sm text-slate-800">{job[0]}</b><p className="mt-1 text-xs text-slate-500">{job[1]} · {job[2]}</p></div><Action onClick={()=>update({...demo,savedJobs:Math.max(0,demo.savedJobs-1)})} secondary>Remove</Action></div>)}</div></Panel>
  if(page==='My profile') return <Panel title="Professional profile" subtitle="Your profile is visible to verified healthcare recruiters."><div className="grid gap-5 md:grid-cols-[180px_1fr]"><div className="rounded-2xl bg-teal-50 p-5 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-teal-700 text-xl font-bold text-white">SJ</div><p className="mt-3 font-bold text-slate-900">Sarah Johnson</p><p className="text-xs text-slate-500">Registered Nurse</p><Pill tone="green">Profile verified</Pill></div><div className="space-y-3"><Info label="Specialty" value="Critical Care & ICU"/><Info label="Experience" value="6 years · Bengaluru, Karnataka"/><Info label="Education" value="Bachelor of Science in Nursing"/><Info label="Skills" value="Patient care · ICU · Electronic records"/><Action onClick={onAction}>Edit profile</Action></div></div></Panel>
  if(page==='Resume') return <Panel title="Resume management" subtitle="Your resume is reviewed before it is shared with recruiters."><div className="flex flex-wrap items-center gap-4 rounded-xl border border-slate-100 p-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><FileText size={20}/></span><div className="flex-1"><p className="text-sm font-bold text-slate-800">Sarah_Johnson_Resume.pdf</p><p className="mt-1 text-xs text-slate-500">Uploaded Oct 07, 2026 · 1.2 MB</p></div><Pill tone={demo.resumeApprove?'green':'amber'}>{demo.resumeApprove?'Approved':'Pending review'}</Pill></div><div className="mt-5 flex flex-wrap gap-2"><Action onClick={onAction}><Upload size={14}/>Upload new resume</Action><Action secondary onClick={onAction}>Preview resume</Action></div><p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">{demo.resumeApprove?'Your approved resume is active and can be used to apply.':'An admin must approve your resume before you can apply for a job.'}</p></Panel>
  return <Panel title="Privacy and discoverability" subtitle="You control what verified recruiters can see."><div className="space-y-3"><Toggle label="Show me in recruiter search" value={demo.privacy.discoverable} onChange={v=>update({...demo,privacy:{...demo.privacy,discoverable:v}})}/><Toggle label="Show resume before I unlock" value={demo.privacy.resumeVisible} onChange={v=>update({...demo,privacy:{...demo.privacy,resumeVisible:v}})}/><Toggle label="Show contact details before unlock" value={demo.privacy.contactVisible} onChange={v=>update({...demo,privacy:{...demo.privacy,contactVisible:v}})}/></div><p className="mt-4 text-xs text-slate-500">These controls update sample preview state only.</p></Panel>
}

function RecruiterScreen({ page, demo, update, onAction }) {
  const [query,setQuery]=useState('')
  if(page==='A–Z Flow') return <Journey role="Recruiter" demo={demo} update={update}/>
  if(page==='Job postings') return <Panel title="Your job postings" subtitle="Draft and track roles across your organization." action={<Action onClick={onAction}>+ Create job</Action>}><Table headers={['Job title','Location','Applicants','Status','Actions']} rows={[["Staff Nurse · ICU","Bengaluru","18 applicants",<Pill tone={demo.jobApprove?'green':'amber'}>{demo.jobApprove?'ACTIVE':demo.jobCreate?'PENDING REVIEW':'DRAFT'}</Pill>,<button onClick={onAction} className="font-semibold text-teal-700">Edit</button>],["Senior Pharmacist","Hyderabad","12 applicants",<Pill tone="green">ACTIVE</Pill>,<button onClick={onAction} className="font-semibold text-teal-700">View</button>]]}/><p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">New jobs are reviewed by MedHire before candidates can see them. Active jobs expire after the configured period.</p></Panel>
  if(['Find candidates','Shortlist'].includes(page)) return <Panel title={page==='Shortlist'?'Shortlisted professionals':'Find healthcare professionals'} subtitle="Search approved candidate profiles matched to your hiring needs." action={<button className="rounded-xl border border-slate-200 p-2 text-slate-500"><Filter size={15}/></button>}><div className="mb-4 relative"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search specialty, skills, or location" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-teal-500"/></div><div className="space-y-3">{[['Emily Chen','Critical Care Nurse · 8 years','Bengaluru · 92% match'],['Aarav Patel','Registered Nurse · 5 years','Hyderabad · 88% match'],['Priya Nair','ICU Nurse · 6 years','Pune · 85% match']].filter(a=>a.join(' ').toLowerCase().includes(query.toLowerCase())).map((a,i)=><article key={a[0]} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-100 p-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-violet-100 text-xs font-bold text-violet-800">{a[0].split(' ').map(x=>x[0]).join('')}</span><div className="flex-1"><p className="text-sm font-bold text-slate-800">{a[0]} <span className="ml-1 text-xs font-medium text-teal-700">{a[2].split(' · ')[1]}</span></p><p className="mt-1 text-xs text-slate-500">{a[1]} · {a[2].split(' · ')[0]}</p></div><Action secondary onClick={()=>update({...demo,savedJobs:demo.savedJobs})}><Heart size={14}/>Shortlist</Action><Action onClick={()=>update({...demo,unlock:true,credits:Math.max(0,demo.credits-1)})}><LockKeyhole size={14}/>{demo.unlock?'Unlocked':'Unlock · 1 credit'}</Action></article>)}</div><p className="mt-4 text-xs text-slate-500">Profile identity is masked until the recruiter unlocks access. Current preview credits: <b>{demo.credits}</b></p></Panel>
  if(page==='Applicants') return <Panel title="Applicants · Staff Nurse ICU" subtitle="Review applications and move candidates through your hiring pipeline."><Table headers={['Candidate','Experience','Applied','Status','Update']} rows={[["Sarah Johnson","6 years","Oct 08, 2026",<Pill tone="blue">{demo.pipeline?demo.appStatus:'Applied'}</Pill>,<button onClick={()=>update({...demo,pipeline:true,appStatus:'Shortlisted',notification:true})} className="font-semibold text-teal-700">Shortlist</button>],["Emily Chen","8 years","Oct 07, 2026",<Pill tone="violet">Interview</Pill>,<button onClick={onAction} className="font-semibold text-teal-700">Review</button>]]}/><p className="mt-4 text-xs text-slate-500">Open an applicant to view the cover letter. Resume and contact details respect the candidate’s privacy settings.</p></Panel>
  if(page==='Plans & credits') return <Panel title="Plans and credits" subtitle="Credits are used when you unlock a candidate profile."><div className="mb-4 rounded-xl bg-teal-50 p-4"><p className="text-xs font-medium text-teal-800">Available credits</p><p className="mt-1 text-3xl font-bold text-teal-900">{demo.credits}</p></div><div className="grid gap-3 md:grid-cols-3">{[['Starter','100 credits','₹4,999'],['Growth','300 credits','₹11,999'],['Enterprise','Custom','Contact us']].map((p,i)=><article key={p[0]} className="rounded-xl border border-slate-200 p-4"><Pill tone={i===1?'teal':'slate'}>{i===1?'Popular':'Plan'}</Pill><h3 className="mt-3 font-bold text-slate-900">{p[0]}</h3><p className="mt-1 text-xs text-slate-500">{p[1]}</p><p className="my-4 text-lg font-bold text-slate-900">{p[2]}</p><Action onClick={()=>update({...demo,checkout:true,credits:demo.credits+(i===0?100:i===1?300:0)})}>Simulate checkout</Action></article>)}</div><p className="mt-4 text-xs text-slate-500">Preview only: no payment provider is contacted.</p></Panel>
  if(page==='Team') return <Panel title="Hiring team" subtitle="Invite colleagues to collaborate on hiring." action={<Action onClick={onAction}>Invite teammate</Action>}><Table headers={['Team member','Role','Status']} rows={[["Anita Sharma","Owner",<Pill tone="green">Active</Pill>],["Karan Shah","Recruiter",<Pill tone="green">Active</Pill>],...demo.teamInvites.map(email=>[email,"Recruiter",<Pill tone="amber">Invited</Pill>])]}/></Panel>
  return <Panel title="Organization profile" subtitle="Verification helps candidates trust your job postings."><div className="grid gap-5 md:grid-cols-[1fr_1fr]"><div className="space-y-3"><Info label="Organization" value="Northstar Medical Group"/><Info label="Registration number" value="KA-HOSP-2021-0842"/><Info label="Website" value="northstarmedical.example"/><Info label="Verification" value={demo.orgApprove?'Approved':demo.orgDocuments?'Documents submitted':'Pending documents'}/></div><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center"><Upload className="mx-auto text-teal-700"/><p className="mt-2 text-sm font-semibold text-slate-800">Registration certificate</p><p className="mt-1 text-xs text-slate-500">PDF or image · private to your organization</p><Action onClick={()=>update({...demo,orgDocuments:true})}>{demo.orgDocuments?'Document uploaded':'Choose a sample document'}</Action></div></div></Panel>
}

function AdminScreen({ page, demo, update, onAction }) {
  if(page==='A–Z Flow') return <Journey role="Admin" demo={demo} update={update}/>
  if(page==='Candidates') return <Panel title="Candidate management" subtitle="Review candidate accounts and resume approvals."><Table headers={['Candidate','Specialty','Resume','Account','Action']} rows={[["Sarah Johnson","Critical Care Nurse",<Pill tone={demo.resumeApprove?'green':'amber'}>{demo.resumeApprove?'APPROVED':'PENDING'}</Pill>,<Pill tone="green">ACTIVE</Pill>,<button onClick={()=>update({...demo,resumeApprove:true})} className="font-semibold text-teal-700">{demo.resumeApprove?'Approved':'Approve resume'}</button>],["Emily Chen","Pediatrics",<Pill tone="green">APPROVED</Pill>,<Pill tone="green">ACTIVE</Pill>,<button onClick={onAction} className="font-semibold text-teal-700">View</button>]]}/></Panel>
  if(page==='Recruiters') return <Panel title="Recruiter verification" subtitle="Review submitted organization details and documents."><div className="space-y-3">{[['Northstar Medical Group','KA-HOSP-2021-0842'],['Sunrise Health Network','MH-HOSP-2024-0021']].map((x,i)=><div key={x[0]} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-100 p-4"><Building2 className="text-teal-700"/><div className="flex-1"><p className="text-sm font-bold text-slate-800">{x[0]}</p><p className="mt-1 text-xs text-slate-500">Registration {x[1]} · {i===0&&demo.orgDocuments?'Documents received':'Submitted today'}</p></div><Pill tone={demo.orgApprove&&i===0?'green':'amber'}>{demo.orgApprove&&i===0?'APPROVED':'PENDING'}</Pill><Action onClick={()=>update({...demo,orgApprove:true})}>{demo.orgApprove&&i===0?'Approved':'Approve'}</Action></div>)}</div></Panel>
  if(page==='Job moderation') return <Panel title="Job moderation queue" subtitle="Approve or reject jobs before they are published."><Table headers={['Position','Organization','Submitted','Status','Action']} rows={[["Staff Nurse · ICU","Northstar Medical Group","Today",<Pill tone={demo.jobApprove?'green':'amber'}>{demo.jobApprove?'ACTIVE':demo.jobCreate?'PENDING':'No new job'}</Pill>,<button onClick={()=>update({...demo,jobApprove:true})} className="font-semibold text-teal-700">{demo.jobApprove?'Approved':'Approve job'}</button>],["Clinical Pharmacist","Green Valley Hospital","Yesterday",<Pill tone="green">ACTIVE</Pill>,<button onClick={onAction} className="font-semibold text-teal-700">Open</button>]]}/></Panel>
  if(page==='Payments') return <Panel title="Payments and credits" subtitle="Review plan purchases and payment activity."><div className="grid gap-3 sm:grid-cols-3"><MiniStat label="Gross revenue" value="₹8,42,500"/><MiniStat label="Successful payments" value="142"/><MiniStat label="Refund requests" value="3"/></div><div className="mt-5"><Table headers={['Organization','Plan','Amount','Status']} rows={[["Northstar Medical Group","Growth · 300 credits","₹11,999",<Pill tone={demo.checkout?'green':'blue'}>{demo.checkout?'PAID':'SUCCESS'}</Pill>],["CityCare Health","Starter · 100 credits","₹4,999",<Pill tone="green">SUCCESS</Pill>]]}/></div></Panel>
  if(page==='Support') return <Panel title="Support inbox" subtitle="Keep track of requests from candidates and recruiters."><Table headers={['Ticket','Requester','Topic','Priority','Status']} rows={[["#MH-2408","Sarah Johnson","Profile visibility","Normal",<Pill tone="amber">OPEN</Pill>],["#MH-2407","Northstar Medical","Organization documents","High",<Pill tone="blue">IN PROGRESS</Pill>]]}/><button onClick={onAction} className="mt-4 text-xs font-semibold text-teal-700">Open selected ticket →</button></Panel>
  if(page==='Staff & roles') return <Panel title="Staff and permissions" subtitle="Manage administrative access by role." action={<Action onClick={onAction}>Invite admin</Action>}><Table headers={['Administrator','Role','Permissions','Status']} rows={[["Rohan Mehta","SUPER_ADMIN","All permissions",<Pill tone="green">ACTIVE</Pill>],["Maya Iyer","VERIFICATION_LEAD","Candidates · Recruiters · Jobs",<Pill tone="green">ACTIVE</Pill>],["Dev Shah","FINANCE_ADMIN","Payments",<Pill tone="green">ACTIVE</Pill>]]}/></Panel>
  return <Panel title="Platform settings" subtitle="Preview editable platform settings and operational controls."><div className="grid gap-5 md:grid-cols-2"><div className="space-y-3"><Toggle label="Maintenance mode" value={demo.settings.maintenance} onChange={v=>update({...demo,settings:{...demo.settings,maintenance:v}})}/><Info label="Platform name" value="MedHire"/><Info label="Support email" value="support@medhire.example"/></div><div className="rounded-xl border border-slate-100 p-4"><label className="text-sm font-semibold text-slate-800">Default job expiry</label><div className="mt-2 flex items-center gap-2"><input type="number" min="1" max="365" value={demo.settings.expiry} onChange={e=>update({...demo,settings:{...demo.settings,expiry:Number(e.target.value)}})} className="w-24 rounded-lg border border-slate-200 px-3 py-2 text-sm"/><span className="text-xs text-slate-500">days after approval</span></div><p className="mt-3 text-xs leading-5 text-slate-500">Changes update local preview state only. Production settings must be saved by an authorized backend operation.</p></div></div></Panel>
}

function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div> }
function MiniStat({ label, value }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div> }
function BriefcaseIcon() { return <Users size={17}/> }
function BellIcon() { return <Clock3 size={14}/> }

export default function PrototypeScreens({ role, page, demo, update, onAction }) {
  if(role==='Candidate') return <CandidateScreen page={page} demo={demo} update={update} onAction={onAction}/>
  if(role==='Recruiter') return <RecruiterScreen page={page} demo={demo} update={update} onAction={onAction}/>
  return <AdminScreen page={page} demo={demo} update={update} onAction={onAction}/>
}

export { defaults as prototypeDefaults, flow as prototypeFlow }
